[build]
  command = "npm run build"  # Netlify가 빌드할 때 사용할 명령어
  publish = ".next"          # 빌드 결과물을 저장하는 디렉토리
  functions = "netlify/functions"  # 서버리스 함수 디렉토리 설정

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Next.js 플러그인 추가

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"  # 모든 요청을 Next.js SSR 핸들러로 리디렉트
  status = 200
